apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/SJoon99/SandBox-Infra
    targetRevision: main
    path: apps/rook-ceph/rook-ceph-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true