apiVersion: v1
kind: Secret
metadata:
  name: harbor-secretkey
  namespace: harbor
type: Opaque
stringData:
  secretKey: "test1234test1234"
  secret: "test1234test1234"
  JOBSERVICE_SECRET: "test1234test1234"
  REGISTRY_HTTP_SECRET: "test1234test1234"
