apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: harbor
type: Opaque
stringData:
  REGISTRY_PASSWD: "test1234"
  REGISTRY_HTPASSWD: "harbor_registry_user:$apr1$VQ9WwAh1$jXS/2NzZVGFyMeFGLNU5w1"
