apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: default
spec:
  gatewayClassName: cilium
  addresses:
  - type: IPAddress
    value: 10.10.0.3
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    # hostname 필드를 아예 제거 (모든 호스트 허용)
    # 또는 allowedRoutes 사용
    allowedRoutes:
      namespaces:
        from: All