apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: advertise-gateway-lb
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:                  
        matchExpressions:
          - key: io.kubernetes.service.namespace
            operator: In
            values: ["default"]
          - key: io.kubernetes.service.name
            operator: In
            values: ["cilium-gateway-cilium-gateway"]
