apiVersion: v1
kind: Pod
metadata:
  name: titan-pvc-test-pod
spec:
  # nodeAffinity를 사용하여 titan-v-server 노드로 강제
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - titan-v-server
  
  containers:
  - name: test-container
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo 'pvc test' >> /data/test.log; sleep 60; done"]
    volumeMounts:
    - mountPath: "/data"
      name: test-volume
  
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: titan-test-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: titan-test-pvc
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block-hot  # Rook-Ceph의 블록 스토리지 클래스 이름