# Default values for gpu-operator.

platform:
  openshift: false

nfd:
  enabled: true
  nodefeaturerules: false

psa:
  enabled: false

cdi:
  enabled: true

sandboxWorkloads:
  enabled: false
  defaultWorkload: "container"

hostPaths:
  rootFS: "/"
  driverInstallDir: "/run/nvidia/driver"

daemonsets:
  priorityClassName: system-node-critical
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  updateStrategy: "RollingUpdate"
  rollingUpdate:
    maxUnavailable: "1"

validator:
  repository: nvcr.io/nvidia/gpu-operator-validator
  tag: v25.3.2
  imagePullSecrets:
    - nvcr-secret
  env:
    - name: WITH_WAIT
      value: "true"
    - name: WAIT_TIMEOUT
      value: "120"   # 드라이버 설치 완료까지 최대 2분 대기

operator:
  repository: nvcr.io/nvidia
  image: gpu-operator
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - nvcr-secret
  priorityClassName: system-node-critical
  runtimeClass: nvidia
  cleanupCRD: false
  upgradeCRD: true
  initContainer:
    repository: nvcr.io/nvidia
    image: cuda
    version: 13.0.1-base-ubi9
    imagePullPolicy: IfNotPresent
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
  annotations:
    openshift.io/scc: restricted-readonly
  logging:
    timeEncoding: epoch
    level: info
    develMode: false
  resources:
    limits:
      cpu: 500m
      memory: 350Mi
    requests:
      cpu: 200m
      memory: 100Mi

mig:
  strategy: single

driver:
  enabled: true
  repository: nvcr.io/nvidia
  image: driver
  version: "580.95.05"
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - nvcr-secret
  kernelModuleType: "auto"
  manager:
    repository: nvcr.io/nvidia/cloud-native
    image: k8s-driver-manager
    version: v0.9.0
    imagePullPolicy: IfNotPresent
    imagePullSecrets:
      - nvcr-secret
  startupProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 60
    failureThreshold: 120
  upgradePolicy:
    autoUpgrade: true
    maxParallelUpgrades: 1
    maxUnavailable: 25%

toolkit:
  enabled: true
  repository: nvcr.io/nvidia/k8s
  image: container-toolkit
  version: v1.18.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - nvcr-secret
  installDir: "/usr/local/nvidia"

devicePlugin:
  enabled: true
  repository: nvcr.io/nvidia
  image: k8s-device-plugin
  version: v0.18.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - nvcr-secret

dcgm:
  enabled: false
  repository: nvcr.io/nvidia/cloud-native
  image: dcgm
  version: 4.4.1-2-ubuntu22.04
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - nvcr-secret

dcgmExporter:
  enabled: true
  repository: nvcr.io/nvidia/k8s
  image: dcgm-exporter
  version: 4.4.1-4.6.0-distroless
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - nvcr-secret

gfd:
  enabled: true
  repository: nvcr.io/nvidia
  image: k8s-device-plugin
  version: v0.18.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - nvcr-secret

migManager:
  enabled: true
  repository: nvcr.io/nvidia/cloud-native
  image: k8s-mig-manager
  version: v0.13.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - nvcr-secret

node-feature-discovery:
  priorityClassName: system-node-critical
  worker:
    serviceAccount:
      name: node-feature-discovery
      create: false
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    config:
      sources:
        pci:
          deviceClassWhitelist:
            - "02"
            - "0200"
            - "0207"
            - "0300"
            - "0302"
          deviceLabelFields:
            - vendor
  master:
    serviceAccount:
      name: node-feature-discovery
      create: true
