apiVersion: v1
kind: Secret
metadata:
  name: rucio-db-secret
  namespace: postgresql
type: kubernetes.io/basic-auth
stringData:
  username: joon
  password: test1234  
---
apiVersion: v1
kind: Secret
metadata:
  name: nessie-db-secret
  namespace: lakehouse
type: kubernetes.io/basic-auth
stringData:
  username: nessie
  password: test1234
