apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-agent-sa
  namespace: default
---
# 1. 권한 부여 (Role)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole 
metadata:
  name: sre-agent-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "nodes", "services"]
    verbs: ["get", "list"]
---
# 2. 권한 연결 (Binding)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sre-agent-binding
subjects:
  - kind: ServiceAccount
    name: sre-agent-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: sre-agent-role
  apiGroup: rbac.authorization.k8s.io
---
# 3. Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-agent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-agent
  template:
    metadata:
      labels:
        app: sre-agent
    spec:
      serviceAccountName: sre-agent-sa  # 위에서 만든 SA 사용
      containers:
        - name: agent
          image: jinkernel/agent:v11  # 빌드한 이미지 주소 
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "200m"
              memory: "1Gi"
---
# 4. Service
apiVersion: v1
kind: Service
metadata:
  name: sre-agent-svc
  namespace: default
spec:
  selector:
    app: sre-agent
  ports:
    - protocol: TCP
      port: 80       # 클러스터 내부에서 부를 포트
      targetPort: 8000