# Ceph Object Store User for Lakehouse
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: pydio
  namespace: rook-ceph
spec:
  store: ceph-objectstore
  displayName: "pydio"
  capabilities:
    user: "*"
    bucket: "*"
    metadata: "*"
    usage: "read"
    zone: "*"
--- 
# Bucket claim for Lakehouse
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: pydio-bucket
  namespace: pydio 
spec:
  bucketName: pydio
  storageClassName: ceph-bucket 