# Ceph Cluster 스펙
cephClusterSpec:
  cephVersion:
    image: quay.io/ceph/ceph:v18 
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      osdsPerDevice: "1"
    nodes:
      - name: "node1"
        devices:
          - name: "/dev/ubuntu-vg/ceph-osd1"
            config:
              deviceClass: "ssd"
          - name: "sdb"
            config:
              deviceClass: "hdd"
      - name: "node2"
        devices:
          - name: "/dev/ubuntu-vg-1/ceph-osd1"
            config:
              deviceClass: "ssd"
          - name: "sdb"
            config:
              deviceClass: "hdd"
      - name: "node4"
        devices:
          - name: "/dev/ubuntu-vg/ceph-osd"
            config:
              deviceClass: "ssd"
      - name: "node5"
        devices:
          - name: "/dev/ubuntu-vg/ceph-osd"
            config:
              deviceClass: "ssd"

