apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    type: storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-operator
  labels:
    pod-security.kubernetes.io/enforce: privileged
    type: gpu
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
  labels:
    type: database
---
apiVersion: v1
kind: Namespace
metadata:
  name: jupyter
  labels:
    type: service
---
apiVersion: v1
kind: Namespace
metadata:
  name: rucio
  labels:
    type: service