apiVersion: ceph.rook.io/v1
kind: CephNFS
metadata:
  name: ceph-nfs-server
  namespace: rook-ceph
spec:
  rados:
    pool: ceph-filesystem-hot-hot-data
    namespace: nfs-ns
  server:
    active: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-nfs
# [중요] Provisioner가 일반 CephFS와 다름
# 기존: rook-ceph.cephfs.csi.ceph.com (X -> 이건 그냥 CephFS 마운트)
# 변경: rook-ceph.nfs.csi.ceph.com    (O -> 이게 NFS Ganesha를 타는 드라이버)
provisioner: rook-ceph.nfs.csi.ceph.com 
parameters:
  nfsCluster: ceph-nfs-server
  sourceName: ceph-filesystem-hot
  clusterID: rook-ceph  
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
--- 
apiVersion: v1
kind: Service
metadata:
  name: ceph-nfs-external-lb  
  namespace: rook-ceph
  annotations:
    io.cilium/lb-ipam-pool: lb-pool-local 
spec:
  type: LoadBalancer
  selector:
    # Rook이 생성한 NFS 파드를 선택하는 라벨 
    app: rook-ceph-nfs
    ceph_nfs: ceph-nfs-server
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-test
spec:
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 1Ti
  storageClassName: rook-ceph-nfs  