# 1) LB-IPAM 풀: LB 타입 Service에 줄 IP 대역
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: bgp-pool-wireguard
spec:
  blocks:
  - cidr: 10.10.0.64/26

---
# 2) BGP v2: 피어 설정 (VPS/FRR 쪽)
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: vps-peer
spec:
  peerASN: 64513
  transport:
    peerAddress: 10.10.0.1
    port: 179
  timers:
    holdTimeSeconds: 90
    keepAliveTimeSeconds: 30
  # eBGP multi-hop이 필요하면 다음 줄 추가
  # ebgpMultihop: true

---
# 3) BGP v2: 클러스터(노드 선택) + 어떤 것을 광고할지
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-to-vps
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: node3   # node3에서만 BGP 스피커
  bgpInstances:
  - name: to-vps
    localASN: 64512
    peers:
    - name: vps
      peerASN: 64513
      peerAddress: 10.10.0.1
      peerConfigRef:
        name: vps-peer
    serviceAdvertisements:
    - selector:
        matchExpressions:
        - key: io.kubernetes.service.type
          operator: In
          values: ["LoadBalancer"]    # LB 서비스 전부 광고
