# 1) LB-IPAM 풀: LB 타입 Service에 줄 IP 대역
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: bgp-pool-wireguard
spec:
  blocks:
  - cidr: 10.10.0.64/26

---
# 2) BGP v2: 피어 설정 (VPS/FRR 쪽)
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: vps-peer
spec:
  timers:
    holdTimeSeconds: 90
    keepAliveTimeSeconds: 30
  transport:
    peerAddress: 10.10.0.1
    peerPort: 179

---
# 3) BGP v2: 클러스터(노드 선택) + 어떤 것을 광고할지
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-to-vps
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: node3 # node3 에서만 BGP 실행
  bgpInstances:
  - name: to-vps
    localASN: 64512
    localPort: 179
    peers:
    - name: vps
      peerASN: 64513
      peerAddress: 10.10.0.1   # VPS FRR의 WG IP
      peerConfigRef:
        name: vps-peer
    serviceAdvertisements:
    - selector: {} # 전체 서비스 광고
      ipPools:
      - bgp-pool-wireguard
