# lb-pool.yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: lb-pool-local
spec:
  blocks:
  - cidr: 10.34.25.0/24 # 10.34.25.0 ~ 10.34.25.255
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-lb
spec:
  loadBalancerIPs: true
  externalIPs: true
  interfaces:
  - ^en.*
  - ^eth.*
  nodeSelector: {}