apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: default   
spec:
  secretName: argocd-tls       
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: argo.jjooniex.org
  dnsNames:
  - argo.jjooniex.org
