apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition # CNI 표준을 따르는 커스텀 리소스, 어떤 네트워크를 어떤 방식으로 추가할지 정의
metadata:
  name: vlan-220-test
  # [중요] 이 NAD를 사용할 Pod이 위치할 네임스페이스와 동일해야 함
  namespace: default 
spec:
  config: |
    {
       "cniVersion": "0.3.1",
       "type": "vlan",
       "master": "enp94s0f1np1",
       "mtu": 9000,
       "vlanId": 220,
       "ipam": {
           "type": "host-local",
           "subnet": "10.50.0.0/24",
           "gateway": "10.50.0.1",
           "rangeStart": "10.50.0.5",
           "rangeEnd": "10.50.0.20"
       }
    }
--- 
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cilium
  namespace: kube-system
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "cilium",
      "type": "cilium-cni",
      "enable-debug": false,
      "log-file": "/var/run/cilium/cilium-cni.log"
    }
---
# Multus CNI 데몬셋이 작동하기 위한 권한 설정
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # 모든 네임스페이스에서 작동
metadata:
  name: multus-cni-role
rules:
# Multus가 Pod의 네트워크 설정을 읽고 쓸 수 있도록 허용
  - apiGroups: [""]
    resources: ["pods", "pods/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: ["network-attachment-definitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
---
# 정의한 ClusterRole을 Multus CNI 서비스 어카운트에 바인딩
# 쿠버네티스는 Role(권한 정의)과 Binding(권한 부여)을 분리
# 그게 ServiceAccount로? (추가 공부)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multus-cni-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multus-cni-role
subjects:
- kind: ServiceAccount
  name: multus-cni
  namespace: kube-system
