apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-220-test
  namespace: weka
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vlan-220-test",
      "type": "ipvlan", 
      "master": "enp94s0f1np1",
      "mode": "l2",
      "mtu": 9000,
      "ipam": {
        "type": "host-local",
        "subnet": "10.50.0.0/24",
        "rangeStart": "10.50.0.21",
        "rangeEnd": "10.50.0.50",
        "gateway": "10.50.0.1"
      }
    }
# macvlan, ipvalan, sriov 등 다양한 CNI 플러그인 사용 가능 
# ipvlan과 macvaln의 성능 차이는 매우 미미함
