apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-220-test
  # [중요] 이 NAD를 사용할 Pod이 위치할 네임스페이스와 동일해야 함
  namespace: default 
spec:
  config: |
    {
       "cniVersion": "0.3.1",
       "type": "vlan",
       "master": "enp94s0f1np1",
       "mtu": 9000,
       "vlanId": 220,
       "ipam": {
           "type": "host-local",
           "subnet": "10.50.0.0/24",
           "gateway": "10.50.0.1",
           "rangeStart": "10.50.0.5",
           "rangeEnd": "10.50.0.20"
       }
    }