argo:
  namespace: argocd
  project: default
  server: https://kubernetes.default.svc
  sourceRepo:
    url: https://github.com/SJoon99/SandBox-Infra.git
    branch: main

applications:
  filestash-object-storage:
    enabled: true
    namespace: filestash
    syncWave: "1"
    source:
      path: argocd/apps/06-DataX-WEKA/storage-config/filestatsh
    syncOptions:
      - CreateNamespace=true
  
  nextcloud-object-storage:
    enabled: true
    namespace: nextcloud
    syncWave: "1"
    source:
      path: argocd/apps/06-DataX-WEKA/storage-config/nextcloud
    syncOptions:
      - CreateNamespace=true

  ocis-object-storage:
    enabled: true
    namespace: ocis
    syncWave: "1"
    source: 
      path: argocd/apps/06-DataX-WEKA/storage-config/ocis
    syncOptions:
      - CreateNamespace=true

  pydio-object-storage:
    enabled: true 
    namespace: pydio
    syncWave: "1"
    source:
      path: argocd/apps/06-DataX-WEKA/storage-config/pydio
    syncOptions:
      - CreateNamespace=true
  
  filestash:
    enabled: true
    namespace: filestash
    syncWave: "2"
    source:
      chart: filestash
      repoURL: https://sebagarayco.github.io/helm-filestash
      targetRevision: 0.2.0
      helm:
        valueFiles:
          - argocd/apps/06-DataX-WEKA/filestash/values.yaml

  nextcloud:
    enabled: true
    namespace: nextcloud 
    syncWave: "3"
    source:
      chart: nextcloud
      repoURL: https://nextcloud.github.io/helm/
      targetRevision: 8.9.1
      helm:
        valueFiles:
          - argocd/apps/06-DataX-WEKA/nextcloud/values.yaml
  
  ocis:
    enabled: true
    namespace: ocis
    syncWave: "4"
    source:
      repoURL: ghcr.io/sjoon99/charts
      chart: ocis
      targetRevision: 0.7.0
      helm:
        valueFiles:
          - argocd/apps/06-DataX-WEKA/ocis/values.yaml
  
  # pydio:
  #   enabled: true
  #   namespace: pydio
  #   syncWave: "5"
  #   source:
  #     chart: cells
  #     repoURL: https://download.pydio.com/pub/charts/helm
  #     targetRevision: 0.1.3
  #     helm:
  #       valueFiles:
  #         - argocd/apps/06-DataX-WEKA/pydio/values.yaml
