apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
type: Opaque
stringData:
  token: "eyJhIjoiNWVlZTBlMThmYTVhMzRmN2ZiMTA3ODlkMTljZWJiZDQiLCJ0IjoiNTEyMzQ2MWYtNTcyZS00Y2U5LWFjNDUtMzA3MjdiYzVkMTEwIiwicyI6Ik5qSTNOVE0wWXpNdE1EQmpaUzAwTkRabUxUazFNbUV0T0RFMU9UWmlZamswTWpjMSJ9"